# Generated by Django 4.2.7 on 2023-11-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clienteAtencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cite',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headLine', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteAtencion.cite')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'verbose_name_plural': 'Ocupaciones',
                'db_table': 'occupation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='typeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'TipoServicio',
                'verbose_name_plural': 'TipoServicios',
                'db_table': 'typeOfService',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteAtencion.occupation')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'Workers',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='cite',
            name='typeOfService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteAtencion.typeofservice'),
        ),
        migrations.AddField(
            model_name='cite',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clienteAtencion.worker'),
        ),
    ]
